name: 'Code Quality'

on:
  pull_request:
  push:

env:
  PHP_VERSION: 8.1
  PHPUNIT_FLAGS: "-v"

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none

      - name: "Install Composer Dependencies"
        uses: ramsey/composer-install@v3

      - name: "Restore PHP-cs-fixer cache results"
        uses: actions/cache/restore@v4
        with:
          path: .cache
          key: 'phpcs-result-cache-${{ github.run_id }}'
          restore-keys: |
            phpcs-result-cache-

      - name: "Run php-cs-fixer"
        run: >-
          vendor/bin/php-cs-fixer fix --diff --dry-run
          --config=.php-cs-fixer.dist.php

      - name: "Save PHP-cs-fixer cache results"
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .cache
          key: 'phpcs-result-cache-${{ github.run_id }}'

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      -   name: "Checkout code"
          uses: actions/checkout@v4

      -   name: "Install PHP"
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ env.PHP_VERSION }}
            coverage: none
            tools: cs2pr

      -   name: "Install Composer Dependencies"
          uses: ramsey/composer-install@v3

      -   name: "Restore PHPStan cache results"
          uses: actions/cache/restore@v4
          with:
            path: .cache/.phpstan.cache
            key: "phpstan-result-cache-${{ github.run_id }}"
            restore-keys: |
              phpstan-result-cache-

      -   name: "Run PHPStan"
          run: vendor/bin/phpstan analyse --no-progress --error-format=checkstyle | cs2pr

      -   name: "Save PHPStan cache results"
          uses: actions/cache/save@v4
          if: always()
          with:
            path: .cache/.phpstan.cache
            key: "phpstan-result-cache-${{ github.run_id }}"

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2
      - name: "Composer install"
        uses: ramsey/composer-install@v3
      - name: "PHPUnit version"
        run: vendor/bin/phpunit --version
      - name: "Run tests"
        run: vendor/bin/phpunit ${{ env.PHPUNIT_FLAGS }}
